# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import SistemaDeEstoques_pb2 as SistemaDeEstoques__pb2

GRPC_GENERATED_VERSION = '1.81.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in SistemaDeEstoques_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class SistemaDeEstoquesStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ConsultarEstoqueGeral = channel.unary_unary(
                '/marmitaria.estoques.v1.SistemaDeEstoques/ConsultarEstoqueGeral',
                request_serializer=SistemaDeEstoques__pb2.ConsultaEstoqueRequest.SerializeToString,
                response_deserializer=SistemaDeEstoques__pb2.EstoqueGeralResponse.FromString,
                _registered_method=True)
        self.ConsultarEstoqueMarmitas = channel.unary_unary(
                '/marmitaria.estoques.v1.SistemaDeEstoques/ConsultarEstoqueMarmitas',
                request_serializer=SistemaDeEstoques__pb2.ConsultaEstoqueRequest.SerializeToString,
                response_deserializer=SistemaDeEstoques__pb2.EstoqueMarmitasResponse.FromString,
                _registered_method=True)
        self.ConsultarEstoqueInsumos = channel.unary_unary(
                '/marmitaria.estoques.v1.SistemaDeEstoques/ConsultarEstoqueInsumos',
                request_serializer=SistemaDeEstoques__pb2.ConsultaEstoqueRequest.SerializeToString,
                response_deserializer=SistemaDeEstoques__pb2.EstoqueInsumosResponse.FromString,
                _registered_method=True)
        self.AjustarEstoqueMarmita = channel.unary_unary(
                '/marmitaria.estoques.v1.SistemaDeEstoques/AjustarEstoqueMarmita',
                request_serializer=SistemaDeEstoques__pb2.AjusteEstoqueMarmitaRequest.SerializeToString,
                response_deserializer=SistemaDeEstoques__pb2.OperacaoEstoqueResponse.FromString,
                _registered_method=True)
        self.AjustarEstoqueInsumo = channel.unary_unary(
                '/marmitaria.estoques.v1.SistemaDeEstoques/AjustarEstoqueInsumo',
                request_serializer=SistemaDeEstoques__pb2.AjusteEstoqueInsumoRequest.SerializeToString,
                response_deserializer=SistemaDeEstoques__pb2.OperacaoEstoqueResponse.FromString,
                _registered_method=True)
        self.DefinirEstoqueMarmitas = channel.unary_unary(
                '/marmitaria.estoques.v1.SistemaDeEstoques/DefinirEstoqueMarmitas',
                request_serializer=SistemaDeEstoques__pb2.DefinirEstoqueMarmitasRequest.SerializeToString,
                response_deserializer=SistemaDeEstoques__pb2.OperacaoEstoqueResponse.FromString,
                _registered_method=True)
        self.DefinirEstoqueInsumos = channel.unary_unary(
                '/marmitaria.estoques.v1.SistemaDeEstoques/DefinirEstoqueInsumos',
                request_serializer=SistemaDeEstoques__pb2.DefinirEstoqueInsumosRequest.SerializeToString,
                response_deserializer=SistemaDeEstoques__pb2.OperacaoEstoqueResponse.FromString,
                _registered_method=True)
        self.ZerarEstoqueMarmitas = channel.unary_unary(
                '/marmitaria.estoques.v1.SistemaDeEstoques/ZerarEstoqueMarmitas',
                request_serializer=SistemaDeEstoques__pb2.OperacaoVaziaRequest.SerializeToString,
                response_deserializer=SistemaDeEstoques__pb2.OperacaoEstoqueResponse.FromString,
                _registered_method=True)
        self.ZerarEstoqueInsumos = channel.unary_unary(
                '/marmitaria.estoques.v1.SistemaDeEstoques/ZerarEstoqueInsumos',
                request_serializer=SistemaDeEstoques__pb2.OperacaoVaziaRequest.SerializeToString,
                response_deserializer=SistemaDeEstoques__pb2.OperacaoEstoqueResponse.FromString,
                _registered_method=True)


class SistemaDeEstoquesServicer:
    """Missing associated documentation comment in .proto file."""

    def ConsultarEstoqueGeral(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ConsultarEstoqueMarmitas(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ConsultarEstoqueInsumos(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AjustarEstoqueMarmita(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AjustarEstoqueInsumo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DefinirEstoqueMarmitas(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DefinirEstoqueInsumos(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ZerarEstoqueMarmitas(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ZerarEstoqueInsumos(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SistemaDeEstoquesServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ConsultarEstoqueGeral': grpc.unary_unary_rpc_method_handler(
                    servicer.ConsultarEstoqueGeral,
                    request_deserializer=SistemaDeEstoques__pb2.ConsultaEstoqueRequest.FromString,
                    response_serializer=SistemaDeEstoques__pb2.EstoqueGeralResponse.SerializeToString,
            ),
            'ConsultarEstoqueMarmitas': grpc.unary_unary_rpc_method_handler(
                    servicer.ConsultarEstoqueMarmitas,
                    request_deserializer=SistemaDeEstoques__pb2.ConsultaEstoqueRequest.FromString,
                    response_serializer=SistemaDeEstoques__pb2.EstoqueMarmitasResponse.SerializeToString,
            ),
            'ConsultarEstoqueInsumos': grpc.unary_unary_rpc_method_handler(
                    servicer.ConsultarEstoqueInsumos,
                    request_deserializer=SistemaDeEstoques__pb2.ConsultaEstoqueRequest.FromString,
                    response_serializer=SistemaDeEstoques__pb2.EstoqueInsumosResponse.SerializeToString,
            ),
            'AjustarEstoqueMarmita': grpc.unary_unary_rpc_method_handler(
                    servicer.AjustarEstoqueMarmita,
                    request_deserializer=SistemaDeEstoques__pb2.AjusteEstoqueMarmitaRequest.FromString,
                    response_serializer=SistemaDeEstoques__pb2.OperacaoEstoqueResponse.SerializeToString,
            ),
            'AjustarEstoqueInsumo': grpc.unary_unary_rpc_method_handler(
                    servicer.AjustarEstoqueInsumo,
                    request_deserializer=SistemaDeEstoques__pb2.AjusteEstoqueInsumoRequest.FromString,
                    response_serializer=SistemaDeEstoques__pb2.OperacaoEstoqueResponse.SerializeToString,
            ),
            'DefinirEstoqueMarmitas': grpc.unary_unary_rpc_method_handler(
                    servicer.DefinirEstoqueMarmitas,
                    request_deserializer=SistemaDeEstoques__pb2.DefinirEstoqueMarmitasRequest.FromString,
                    response_serializer=SistemaDeEstoques__pb2.OperacaoEstoqueResponse.SerializeToString,
            ),
            'DefinirEstoqueInsumos': grpc.unary_unary_rpc_method_handler(
                    servicer.DefinirEstoqueInsumos,
                    request_deserializer=SistemaDeEstoques__pb2.DefinirEstoqueInsumosRequest.FromString,
                    response_serializer=SistemaDeEstoques__pb2.OperacaoEstoqueResponse.SerializeToString,
            ),
            'ZerarEstoqueMarmitas': grpc.unary_unary_rpc_method_handler(
                    servicer.ZerarEstoqueMarmitas,
                    request_deserializer=SistemaDeEstoques__pb2.OperacaoVaziaRequest.FromString,
                    response_serializer=SistemaDeEstoques__pb2.OperacaoEstoqueResponse.SerializeToString,
            ),
            'ZerarEstoqueInsumos': grpc.unary_unary_rpc_method_handler(
                    servicer.ZerarEstoqueInsumos,
                    request_deserializer=SistemaDeEstoques__pb2.OperacaoVaziaRequest.FromString,
                    response_serializer=SistemaDeEstoques__pb2.OperacaoEstoqueResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'marmitaria.estoques.v1.SistemaDeEstoques', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('marmitaria.estoques.v1.SistemaDeEstoques', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SistemaDeEstoques:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ConsultarEstoqueGeral(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/marmitaria.estoques.v1.SistemaDeEstoques/ConsultarEstoqueGeral',
            SistemaDeEstoques__pb2.ConsultaEstoqueRequest.SerializeToString,
            SistemaDeEstoques__pb2.EstoqueGeralResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ConsultarEstoqueMarmitas(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/marmitaria.estoques.v1.SistemaDeEstoques/ConsultarEstoqueMarmitas',
            SistemaDeEstoques__pb2.ConsultaEstoqueRequest.SerializeToString,
            SistemaDeEstoques__pb2.EstoqueMarmitasResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ConsultarEstoqueInsumos(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/marmitaria.estoques.v1.SistemaDeEstoques/ConsultarEstoqueInsumos',
            SistemaDeEstoques__pb2.ConsultaEstoqueRequest.SerializeToString,
            SistemaDeEstoques__pb2.EstoqueInsumosResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AjustarEstoqueMarmita(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/marmitaria.estoques.v1.SistemaDeEstoques/AjustarEstoqueMarmita',
            SistemaDeEstoques__pb2.AjusteEstoqueMarmitaRequest.SerializeToString,
            SistemaDeEstoques__pb2.OperacaoEstoqueResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AjustarEstoqueInsumo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/marmitaria.estoques.v1.SistemaDeEstoques/AjustarEstoqueInsumo',
            SistemaDeEstoques__pb2.AjusteEstoqueInsumoRequest.SerializeToString,
            SistemaDeEstoques__pb2.OperacaoEstoqueResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DefinirEstoqueMarmitas(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/marmitaria.estoques.v1.SistemaDeEstoques/DefinirEstoqueMarmitas',
            SistemaDeEstoques__pb2.DefinirEstoqueMarmitasRequest.SerializeToString,
            SistemaDeEstoques__pb2.OperacaoEstoqueResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DefinirEstoqueInsumos(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/marmitaria.estoques.v1.SistemaDeEstoques/DefinirEstoqueInsumos',
            SistemaDeEstoques__pb2.DefinirEstoqueInsumosRequest.SerializeToString,
            SistemaDeEstoques__pb2.OperacaoEstoqueResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ZerarEstoqueMarmitas(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/marmitaria.estoques.v1.SistemaDeEstoques/ZerarEstoqueMarmitas',
            SistemaDeEstoques__pb2.OperacaoVaziaRequest.SerializeToString,
            SistemaDeEstoques__pb2.OperacaoEstoqueResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ZerarEstoqueInsumos(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/marmitaria.estoques.v1.SistemaDeEstoques/ZerarEstoqueInsumos',
            SistemaDeEstoques__pb2.OperacaoVaziaRequest.SerializeToString,
            SistemaDeEstoques__pb2.OperacaoEstoqueResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
